# -*- coding: utf-8 -*-
"""trabalho_karla.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j7NPprZhbQjq0sRzakvQAa6lf-LkVG8U
"""

import sqlite3
import pandas as pd
import numpy as np
import math
import json
from datetime import datetime

# BANCO DE DADOS

conn = sqlite3.connect("estoque.db")
cursor = conn.cursor()

# Tabela de produtos

cursor.execute("""
CREATE TABLE IF NOT EXISTS produtos (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    nome TEXT,
    quantidade INTEGER,
    preco REAL,
    estoque_min INTEGER
)
""")

# Tabela de histórico

cursor.execute("""
CREATE TABLE IF NOT EXISTS movimentacoes (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    produto_id INTEGER,
    tipo TEXT,
    quantidade INTEGER,
    data TEXT
)
""")

conn.commit()

# FUNÇÕES 

def adicionar_produto(nome, quantidade, preco, estoque_min): 
    cursor.execute("""
    INSERT INTO produtos (nome, quantidade, preco, estoque_min)
    VALUES (?, ?, ?, ?)
    """, (nome, quantidade, preco, estoque_min))
    conn.commit()
    print("Produto cadastrado!")

def registrar_movimentacao(produto_id, tipo, quantidade):
    data = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    cursor.execute("""
    INSERT INTO movimentacoes (produto_id, tipo, quantidade, data)
    VALUES (?, ?, ?, ?)
    """, (produto_id, tipo, quantidade, data))
    conn.commit() 

def entrada_produto(id_produto, quantidade):
    cursor.execute("SELECT quantidade FROM produtos WHERE id = ?", (id_produto,))
    resultado = cursor.fetchone()

    if resultado:
        nova_qtd = resultado[0] + quantidade
        cursor.execute("UPDATE produtos SET quantidade = ? WHERE id = ?", (nova_qtd, id_produto))
        conn.commit()
        registrar_movimentacao(id_produto, "entrada", quantidade)
        print("Entrada realizada!")
    else:
        print("Produto não encontrado!")

def saida_produto(id_produto, quantidade): 
    cursor.execute("SELECT quantidade FROM produtos WHERE id = ?", (id_produto,))
    resultado = cursor.fetchone()

    if resultado:
        if resultado[0] >= quantidade:
            nova_qtd = resultado[0] - quantidade
            cursor.execute("UPDATE produtos SET quantidade = ? WHERE id = ?", (nova_qtd, id_produto))
            conn.commit()
            registrar_movimentacao(id_produto, "saida", quantidade)
            print("Saída realizada!")
        else:
            print("Estoque insuficiente!")
    else:
        print("Produto não encontrado!")

def listar_produtos():
    df = pd.read_sql_query("SELECT * FROM produtos", conn)
    print("\n=== ESTOQUE ===")
    print(df)

    # ALERTA DE ESTOQUE BAIXO

    baixos = df[df["quantidade"] <= df["estoque_min"]]
    if not baixos.empty:
        print("\n⚠️ ALERTA: Estoque baixo!")
        print(baixos)

    return df

def historico():
    df = pd.read_sql_query("SELECT * FROM movimentacoes", conn)
    print("\n=== HISTÓRICO ===")
    print(df)

def calcular_total(df):
    total = np.sum(df["quantidade"] * df["preco"])
    print(f"Total em estoque: R${total:.2f}")

def media_precos(df):
    if len(df) > 0:
        media = math.fsum(df["preco"]) / len(df)
        print(f"Média de preços: R${media:.2f}")

def exportar_json(df):
    dados = df.to_dict(orient="records")
    with open("estoque.json", "w") as f:
        json.dump(dados, f, indent=4)
    print("Exportado para JSON!")

# MENU

while True:
    print("\n1 - Cadastrar Produto")
    print("2 - Entrada")
    print("3 - Saída")
    print("4 - Listar Estoque")
    print("5 - Valor Total")
    print("6 - Média de Preços")
    print("7 - Histórico")
    print("8 - Exportar JSON")
    print("0 - Sair")

    opcao = input("Escolha: ")

    if opcao == "1":
        nome = input("Nome: ")
        quantidade = int(input("Quantidade: "))
        preco = float(input("Preço: "))
        estoque_min = int(input("Estoque mínimo: "))
        adicionar_produto(nome, quantidade, preco, estoque_min)

    elif opcao == "2":
        id_produto = int(input("ID: "))
        qtd = int(input("Quantidade: "))
        entrada_produto(id_produto, qtd)

    elif opcao == "3":
        id_produto = int(input("ID: "))
        qtd = int(input("Quantidade: "))
        saida_produto(id_produto, qtd)

    elif opcao == "4":
        listar_produtos()

    elif opcao == "5":
        df = listar_produtos()
        calcular_total(df)

    elif opcao == "6":
        df = listar_produtos()
        media_precos(df)

    elif opcao == "7":
        historico()

    elif opcao == "8":
        df = listar_produtos()
        exportar_json(df)

    elif opcao == "0":
        break

    else:
        print("Opção inválida!") 
